name: ResourceWorld
version: 1.0.0
main: me.nik.resourceworld.ResourceWorld
api-version: 1.13
load: POSTWORLD
authors: [Nik]
description: Unlimited resources!
commands:
  resource:
    description: Unlimited resources!
    usage: /<command> <subcommand>
    aliases:
      - rw
      - resourceworld
