name: ResourceWorld
version: 1.2.4
main: me.nik.resourceworld.ResourceWorld
api-version: 1.13
load: POSTWORLD
authors: [Nik]
description: Unlimited resources!
commands:
  resource:
    description: Unlimited resources!
    usage: /<command>
    aliases:
      - rw
      - resourceworld
permissions:
  rw.tp:
    description: Randomly Teleport To The Resource World!
    default: true
  rw.admin:
    description: Access to the Resource World admin commands!
    default: op
